### ISSUE TITLE
Text area in new note dialog is resizable

### ISSUE THREAD

**Issue by rohmulan** [thewhitetulip/omninotesweb#5]
So a user can do that :
![screenshot from 2015-01-20 23 57 36](https://cloud.githubusercontent.com/assets/7365362/5823110/213ac110-a100-11e4-9a55-486bad0259ca.png)

**Comment by thewhitetulip** [comment]
Fixed https://github.com/thewhitetulip/omninotesweb/commit/5e3fbc175f63a2c569821a53e44ab546363a3edd
